name: Test Content Generation

on:
  workflow_dispatch:  # Manual trigger for testing

jobs:
  test_generation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Generate daily content
        run: python scripts/generate_content.py
        
      - name: Create blog post
        run: python scripts/create_post.py
        
      - name: Show generated content
        run: cat content.json
        
      - name: Show created post
        run: cat _posts/*-daily-motivation.md
